name: segunda-practica-ia-software-abierto
services:
  grobid:
    container_name: grobid_ia_2
    image: grobid/grobid:0.8.2-full
    restart: always
    ports:
      - "${GROBID_EXTERNAL_PORT}:8070"
    networks:
      - net_ia_practica_2

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 10s    
      timeout: 5s     
      retries: 10      
      start_period: 30s
    init: true
    ulimits:
      core: 0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  python-xml: 
    container_name: python_xml
    build: ./pygrobid/
    depends_on:
      grobid:
        condition: service_healthy 
    environment:
      GROBID_URL: "http://grobid:8070/api/processFulltextDocument"
      CANTIDAD_PALABRAS: ${CANTIDAD_PALABRAS}
    volumes:
      - ./pygrobid/input:/input
      - ./pygrobid/output:/output
    networks:
      - net_ia_practica_2

  python-data:
    container_name: python_data
    build: ./pyextractdata/
    depends_on:
      python-xml:
        condition: service_completed_successfully # Exit 0 del proceso de python-xml.
    volumes:
      - ./pygrobid/output/:/input
      - ./pyextractdata/output:/output
    networks:
      - net_ia_practica_2

  python-orcid:
    container_name: python_orcid
    build: ./pyorcid/
    depends_on:
      python-data:
        condition: service_completed_successfully # Exit 0 del proceso de python-data.
    volumes:
      - ./pyextractdata/output/:/input
      - ./pyorcid/output:/output
    networks:
      - net_ia_practica_2
    environment:
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      CLIENT_URL: ${CLIENT_URL}

  python-wikidata:
    container_name: python_wikidata
    build: ./pywikidata/
    depends_on: 
      python-orcid:
        condition: service_completed_successfully
    volumes:
      - ./pyextractdata/output/:/input
      - ./pywikidata/output:/output
    networks:
      - net_ia_practica_2


  python-openalex:
    container_name: python_openalex
    build: ./pyopenalex/
    depends_on:
      python-data:
        condition: service_completed_successfully
    volumes:
      - ./pyextractdata/output:/input
      - ./pyopenalex/output:/output
    networks:
      - net_ia_practica_2

  python-clustering:
    container_name: python_clustering
    build: ./pyclustering/
    depends_on:
      python-data:
        condition: service_completed_successfully
    volumes:
      - ./pyextractdata/output:/input
      - ./pyclustering/output:/output
    networks:
      - net_ia_practica_2

networks:
  net_ia_practica_2:
    driver: bridge
